tableName: superstore_orders
primaryKey: row_id
selector: type="superstore_order"
attributes:
- fieldName: row_id
  sourceName: /data/row_id
  mappingStrategy: IntBSI
  type: Integer
  columnID: true
  sourceOrdinal: 1
- fieldName: order_id
  sourceName: /data/order_id
  mappingStrategy: StringLexBSI
  configuration:
    length: "14"
  type: String
  maxLen: 32
  sourceOrdinal: 2
- fieldName: order_date
  sourceName: /data/order_date
  mappingStrategy: TimestampBSI
  configuration:
    granularity: "second"
  type: Date
  sourceOrdinal: 3
- fieldName: ship_date
  sourceName: /data/ship_date
  mappingStrategy: TimestampBSI
  configuration:
    granularity: "second"
  type: Date
  sourceOrdinal: 4
- fieldName: ship_mode
  sourceName: /data/ship_mode
  mappingStrategy: StringEnum
  type: String
  sourceOrdinal: 5
- fieldName: customer_id
  sourceName: /data/customer_id
  mappingStrategy: StringLexBSI
  configuration:
    length: "8"
  type: String
  maxLen: 32
  sourceOrdinal: 6
- fieldName: customer_name
  sourceName: /data/customer_name
  mappingStrategy: StringLexBSI
  configuration:
    length: "16"
  type: String
  maxLen: 128
  sourceOrdinal: 7
- fieldName: segment
  sourceName: /data/segment
  mappingStrategy: StringEnum
  type: String
  sourceOrdinal: 8
- fieldName: country_region
  sourceName: /data/country_region
  mappingStrategy: StringEnum
  type: String
  sourceOrdinal: 9
- fieldName: city
  sourceName: /data/city
  mappingStrategy: StringEnum
  type: String
  sourceOrdinal: 10
- fieldName: state_province
  sourceName: /data/state_province
  mappingStrategy: StringEnum
  type: String
  sourceOrdinal: 11
- fieldName: postal_code
  sourceName: /data/postal_code
  mappingStrategy: StringEnum
  type: String
  sourceOrdinal: 12
- fieldName: region
  sourceName: /data/region
  mappingStrategy: StringEnum
  type: String
  sourceOrdinal: 13
- fieldName: product_id
  sourceName: /data/product_id
  mappingStrategy: StringLexBSI
  configuration:
    length: "16"
  type: String
  maxLen: 64
  sourceOrdinal: 14
- fieldName: category
  sourceName: /data/category
  mappingStrategy: StringEnum
  type: String
  sourceOrdinal: 15
- fieldName: sub_category
  sourceName: /data/sub_category
  mappingStrategy: StringEnum
  type: String
  sourceOrdinal: 16
- fieldName: product_name
  sourceName: /data/product_name
  mappingStrategy: StringLexBSI
  configuration:
    length: "24"
  type: String
  maxLen: 256
  sourceOrdinal: 17
- fieldName: sales
  sourceName: /data/sales
  mappingStrategy: FloatScaleBSI
  type: Float
  scale: 2
  sourceOrdinal: 18
- fieldName: quantity
  sourceName: /data/quantity
  mappingStrategy: IntBSI
  type: Integer
  sourceOrdinal: 19
- fieldName: discount
  sourceName: /data/discount
  mappingStrategy: FloatScaleBSI
  type: Float
  scale: 4
  sourceOrdinal: 20
- fieldName: profit
  sourceName: /data/profit
  mappingStrategy: FloatScaleBSI
  type: Float
  scale: 2
  sourceOrdinal: 21
