#!/usr/bin/env python3
"""Convert QuantaStream MySQL command traces into a SQLRunner draft suite."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path
from typing import Iterable

import summarize_mysql_trace as trace

QUERY_KEYWORDS = {"select", "show", "describe", "desc", "explain", "with"}
SKIPPED_SQL_PREFIXES = ("commit", "rollback")


def load_events(paths: list[Path]) -> list[trace.TraceEvent]:
    if not paths:
        return list(trace.iter_events([]))
    events: list[trace.TraceEvent] = []
    for path in paths:
        if path.suffix.lower() in {".jsonl", ".ndjson"}:
            events.extend(load_events_jsonl(path))
        else:
            events.extend(trace.iter_events([path]))
    return events


def load_events_jsonl(path: Path) -> Iterable[trace.TraceEvent]:
    with path.open("r", encoding="utf-8", errors="replace") as handle:
        for line_number, line in enumerate(handle, 1):
            line = line.strip()
            if not line:
                continue
            row = json.loads(line)
            yield trace.TraceEvent(
                source=row.get("source", str(path)),
                line_number=int(row.get("line_number", line_number)),
                connection_id=str(row.get("connection_id", "")),
                user=str(row.get("user", "")),
                db=str(row.get("db", "")),
                kind=str(row.get("kind", "")),
                sql=str(row.get("sql", "")),
                statement_id=str(row.get("statement_id", "")),
                parameter_id=str(row.get("parameter_id", "")),
                long_data_bytes=str(row.get("long_data_bytes", "")),
                response=str(row.get("response", "")),
                elapsed=str(row.get("elapsed", "")),
                error=str(row.get("error", "")),
            )


def sqlrunner_kind(sql: str) -> str:
    keyword = first_keyword(sql)
    if keyword in QUERY_KEYWORDS:
        return "query"
    return "statement"


def first_keyword(sql: str) -> str:
    match = re.search(r"[A-Za-z_]+", sql.lstrip("( \t\r\n"))
    return match.group(0).lower() if match else "sql"


def sql_slug(sql: str) -> str:
    words = re.findall(r"[A-Za-z0-9_]+", trace.normalize_sql(sql).lower())
    words = [word for word in words if word not in {"select", "from", "where", "as", "the"}]
    slug = "_".join(words[:4]) or first_keyword(sql) or "sql"
    slug = re.sub(r"_+", "_", slug).strip("_")
    digest = hashlib.sha1(trace.normalize_sql(sql).encode("utf-8")).hexdigest()[:8]
    return f"{slug}_{digest}"


def should_skip_sql(sql: str) -> bool:
    normalized = trace.normalize_sql(sql).lower()
    return not normalized or any(normalized.startswith(prefix) for prefix in SKIPPED_SQL_PREFIXES)


def unique_sql_events(events: list[trace.TraceEvent], include_errors: bool) -> list[trace.TraceEvent]:
    by_sql: dict[str, trace.TraceEvent] = {}
    for event in events:
        if event.kind not in {"query", "stmt_prepare"}:
            continue
        if not event.sql or should_skip_sql(event.sql):
            continue
        if event.response == "error" and not include_errors:
            continue
        key = trace.normalize_sql(event.sql).lower()
        by_sql.setdefault(key, event)
    return sorted(by_sql.values(), key=lambda event: (event.source, event.line_number, trace.normalize_sql(event.sql).lower()))


def render_suite(events: list[trace.TraceEvent], suite_name: str, feature: str, include_errors: bool) -> str:
    selected = unique_sql_events(events, include_errors=include_errors)
    lines: list[str] = []
    lines.append("# Generated by scripts/trace_to_sqlrunner.py.")
    lines.append("# Review IDs, features, and expected results before moving this into the QuantaStream engine repo.")
    lines.append("version: 1")
    lines.append(f"name: {suite_name}")
    lines.append("")
    lines.append("tests:")
    if not selected:
        lines.append("  []")
        return "\n".join(lines) + "\n"

    for index, event in enumerate(selected, 1):
        sql = trace.normalize_sql(event.sql)
        case_id = f"{suite_name}.{index:03d}.{sql_slug(sql)}"
        response_error = event.response == "error"
        status = "xfail" if response_error else "supported"
        lines.append(f"  - id: {case_id}")
        lines.append(f"    status: {status}")
        lines.append(f"    kind: {sqlrunner_kind(sql)}")
        lines.append(f"    feature: {feature}")
        lines.append("    compatibility: mysql")
        lines.append("    requires: [tableau_capture]")
        lines.append("    sql: |")
        for sql_line in sql.splitlines() or [sql]:
            lines.append(f"      {sql_line}")
        if response_error:
            lines.append("    expect:")
            lines.append(f"      error: {yaml_scalar(event.error or 'error')}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def yaml_scalar(value: str) -> str:
    value = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{value}"'


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate a SQLRunner draft suite from QS MYSQL_COMMAND_TRACE logs or events JSONL.")
    parser.add_argument("paths", nargs="*", type=Path, help="Trace log or events JSONL files. Reads stdin as trace log when omitted.")
    parser.add_argument("--suite-name", default="mysql_compat_tableau_capture")
    parser.add_argument("--feature", default="tableau_trace_replay")
    parser.add_argument("--include-errors", action="store_true", help="Include SQL commands that produced MySQL error responses as xfail cases.")
    parser.add_argument("--out", type=Path, help="Output YAML path. Prints to stdout when omitted.")
    args = parser.parse_args(argv)

    suite = render_suite(load_events(args.paths), args.suite_name, args.feature, args.include_errors)
    if args.out:
        args.out.write_text(suite, encoding="utf-8")
    else:
        sys.stdout.write(suite)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
